/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterRegisterSubdomainImport } from './routes/_register/registerSubdomain'
import { Route as RegisterRegisterAccountImport } from './routes/_register/registerAccount'
import { Route as ComponentsPlansImport } from './routes/_components/Plans'
import { Route as ComponentsModalImport } from './routes/_components/Modal'
import { Route as ComponentsInputImport } from './routes/_components/Input'
import { Route as ComponentsFeaturesImport } from './routes/_components/Features'
import { Route as AuthVehiclesIndexImport } from './routes/_auth/vehicles/index'
import { Route as AuthServicesIndexImport } from './routes/_auth/services/index'
import { Route as AuthMechanicalsIndexImport } from './routes/_auth/mechanicals/index'
import { Route as AuthDashboardIndexImport } from './routes/_auth/dashboard/index'
import { Route as AuthClientsIndexImport } from './routes/_auth/clients/index'
import { Route as AuthGoogleCallbackImport } from './routes/auth/google/callback'
import { Route as AuthServicesQuotesIndexImport } from './routes/_auth/services/quotes/index'
import { Route as AuthServicesOngoingIndexImport } from './routes/_auth/services/ongoing/index'
import { Route as AuthServicesHistoryIndexImport } from './routes/_auth/services/history/index'
import { Route as AuthDashboardReportsServicesIndexImport } from './routes/_auth/dashboard/reports-services/index'
import { Route as AuthDashboardReportsOperationIndexImport } from './routes/_auth/dashboard/reports-operation/index'
import { Route as AuthDashboardReportsMechanicalsIndexImport } from './routes/_auth/dashboard/reports-mechanicals/index'
import { Route as AuthMechanicalsComponentsCreateImport } from './routes/_auth/mechanicals/_components/create'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRegisterSubdomainRoute = RegisterRegisterSubdomainImport.update({
  path: '/registerSubdomain',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRegisterAccountRoute = RegisterRegisterAccountImport.update({
  path: '/registerAccount',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsPlansRoute = ComponentsPlansImport.update({
  path: '/Plans',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsModalRoute = ComponentsModalImport.update({
  path: '/Modal',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsInputRoute = ComponentsInputImport.update({
  path: '/Input',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsFeaturesRoute = ComponentsFeaturesImport.update({
  path: '/Features',
  getParentRoute: () => rootRoute,
} as any)

const AuthVehiclesIndexRoute = AuthVehiclesIndexImport.update({
  path: '/vehicles/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthServicesIndexRoute = AuthServicesIndexImport.update({
  path: '/services/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMechanicalsIndexRoute = AuthMechanicalsIndexImport.update({
  path: '/mechanicals/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardIndexRoute = AuthDashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthClientsIndexRoute = AuthClientsIndexImport.update({
  path: '/clients/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthGoogleCallbackRoute = AuthGoogleCallbackImport.update({
  path: '/auth/google/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthServicesQuotesIndexRoute = AuthServicesQuotesIndexImport.update({
  path: '/services/quotes/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthServicesOngoingIndexRoute = AuthServicesOngoingIndexImport.update({
  path: '/services/ongoing/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthServicesHistoryIndexRoute = AuthServicesHistoryIndexImport.update({
  path: '/services/history/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardReportsServicesIndexRoute =
  AuthDashboardReportsServicesIndexImport.update({
    path: '/dashboard/reports-services/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthDashboardReportsOperationIndexRoute =
  AuthDashboardReportsOperationIndexImport.update({
    path: '/dashboard/reports-operation/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthDashboardReportsMechanicalsIndexRoute =
  AuthDashboardReportsMechanicalsIndexImport.update({
    path: '/dashboard/reports-mechanicals/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthMechanicalsComponentsCreateRoute =
  AuthMechanicalsComponentsCreateImport.update({
    path: '/mechanicals/create',
    getParentRoute: () => AuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_components/Features': {
      id: '/_components/Features'
      path: '/Features'
      fullPath: '/Features'
      preLoaderRoute: typeof ComponentsFeaturesImport
      parentRoute: typeof rootRoute
    }
    '/_components/Input': {
      id: '/_components/Input'
      path: '/Input'
      fullPath: '/Input'
      preLoaderRoute: typeof ComponentsInputImport
      parentRoute: typeof rootRoute
    }
    '/_components/Modal': {
      id: '/_components/Modal'
      path: '/Modal'
      fullPath: '/Modal'
      preLoaderRoute: typeof ComponentsModalImport
      parentRoute: typeof rootRoute
    }
    '/_components/Plans': {
      id: '/_components/Plans'
      path: '/Plans'
      fullPath: '/Plans'
      preLoaderRoute: typeof ComponentsPlansImport
      parentRoute: typeof rootRoute
    }
    '/_register/registerAccount': {
      id: '/_register/registerAccount'
      path: '/registerAccount'
      fullPath: '/registerAccount'
      preLoaderRoute: typeof RegisterRegisterAccountImport
      parentRoute: typeof rootRoute
    }
    '/_register/registerSubdomain': {
      id: '/_register/registerSubdomain'
      path: '/registerSubdomain'
      fullPath: '/registerSubdomain'
      preLoaderRoute: typeof RegisterRegisterSubdomainImport
      parentRoute: typeof rootRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_auth/clients/': {
      id: '/_auth/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthClientsIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/mechanicals/': {
      id: '/_auth/mechanicals/'
      path: '/mechanicals'
      fullPath: '/mechanicals'
      preLoaderRoute: typeof AuthMechanicalsIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/services/': {
      id: '/_auth/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthServicesIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/vehicles/': {
      id: '/_auth/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthVehiclesIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/mechanicals/_components/create': {
      id: '/_auth/mechanicals/_components/create'
      path: '/mechanicals/create'
      fullPath: '/mechanicals/create'
      preLoaderRoute: typeof AuthMechanicalsComponentsCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/reports-mechanicals/': {
      id: '/_auth/dashboard/reports-mechanicals/'
      path: '/dashboard/reports-mechanicals'
      fullPath: '/dashboard/reports-mechanicals'
      preLoaderRoute: typeof AuthDashboardReportsMechanicalsIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/reports-operation/': {
      id: '/_auth/dashboard/reports-operation/'
      path: '/dashboard/reports-operation'
      fullPath: '/dashboard/reports-operation'
      preLoaderRoute: typeof AuthDashboardReportsOperationIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/reports-services/': {
      id: '/_auth/dashboard/reports-services/'
      path: '/dashboard/reports-services'
      fullPath: '/dashboard/reports-services'
      preLoaderRoute: typeof AuthDashboardReportsServicesIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/services/history/': {
      id: '/_auth/services/history/'
      path: '/services/history'
      fullPath: '/services/history'
      preLoaderRoute: typeof AuthServicesHistoryIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/services/ongoing/': {
      id: '/_auth/services/ongoing/'
      path: '/services/ongoing'
      fullPath: '/services/ongoing'
      preLoaderRoute: typeof AuthServicesOngoingIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/services/quotes/': {
      id: '/_auth/services/quotes/'
      path: '/services/quotes'
      fullPath: '/services/quotes'
      preLoaderRoute: typeof AuthServicesQuotesIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthClientsIndexRoute: typeof AuthClientsIndexRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthMechanicalsIndexRoute: typeof AuthMechanicalsIndexRoute
  AuthServicesIndexRoute: typeof AuthServicesIndexRoute
  AuthVehiclesIndexRoute: typeof AuthVehiclesIndexRoute
  AuthMechanicalsComponentsCreateRoute: typeof AuthMechanicalsComponentsCreateRoute
  AuthDashboardReportsMechanicalsIndexRoute: typeof AuthDashboardReportsMechanicalsIndexRoute
  AuthDashboardReportsOperationIndexRoute: typeof AuthDashboardReportsOperationIndexRoute
  AuthDashboardReportsServicesIndexRoute: typeof AuthDashboardReportsServicesIndexRoute
  AuthServicesHistoryIndexRoute: typeof AuthServicesHistoryIndexRoute
  AuthServicesOngoingIndexRoute: typeof AuthServicesOngoingIndexRoute
  AuthServicesQuotesIndexRoute: typeof AuthServicesQuotesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthClientsIndexRoute: AuthClientsIndexRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthMechanicalsIndexRoute: AuthMechanicalsIndexRoute,
  AuthServicesIndexRoute: AuthServicesIndexRoute,
  AuthVehiclesIndexRoute: AuthVehiclesIndexRoute,
  AuthMechanicalsComponentsCreateRoute: AuthMechanicalsComponentsCreateRoute,
  AuthDashboardReportsMechanicalsIndexRoute:
    AuthDashboardReportsMechanicalsIndexRoute,
  AuthDashboardReportsOperationIndexRoute:
    AuthDashboardReportsOperationIndexRoute,
  AuthDashboardReportsServicesIndexRoute:
    AuthDashboardReportsServicesIndexRoute,
  AuthServicesHistoryIndexRoute: AuthServicesHistoryIndexRoute,
  AuthServicesOngoingIndexRoute: AuthServicesOngoingIndexRoute,
  AuthServicesQuotesIndexRoute: AuthServicesQuotesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/Features': typeof ComponentsFeaturesRoute
  '/Input': typeof ComponentsInputRoute
  '/Modal': typeof ComponentsModalRoute
  '/Plans': typeof ComponentsPlansRoute
  '/registerAccount': typeof RegisterRegisterAccountRoute
  '/registerSubdomain': typeof RegisterRegisterSubdomainRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/clients': typeof AuthClientsIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/mechanicals': typeof AuthMechanicalsIndexRoute
  '/services': typeof AuthServicesIndexRoute
  '/vehicles': typeof AuthVehiclesIndexRoute
  '/mechanicals/create': typeof AuthMechanicalsComponentsCreateRoute
  '/dashboard/reports-mechanicals': typeof AuthDashboardReportsMechanicalsIndexRoute
  '/dashboard/reports-operation': typeof AuthDashboardReportsOperationIndexRoute
  '/dashboard/reports-services': typeof AuthDashboardReportsServicesIndexRoute
  '/services/history': typeof AuthServicesHistoryIndexRoute
  '/services/ongoing': typeof AuthServicesOngoingIndexRoute
  '/services/quotes': typeof AuthServicesQuotesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/Features': typeof ComponentsFeaturesRoute
  '/Input': typeof ComponentsInputRoute
  '/Modal': typeof ComponentsModalRoute
  '/Plans': typeof ComponentsPlansRoute
  '/registerAccount': typeof RegisterRegisterAccountRoute
  '/registerSubdomain': typeof RegisterRegisterSubdomainRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/clients': typeof AuthClientsIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/mechanicals': typeof AuthMechanicalsIndexRoute
  '/services': typeof AuthServicesIndexRoute
  '/vehicles': typeof AuthVehiclesIndexRoute
  '/mechanicals/create': typeof AuthMechanicalsComponentsCreateRoute
  '/dashboard/reports-mechanicals': typeof AuthDashboardReportsMechanicalsIndexRoute
  '/dashboard/reports-operation': typeof AuthDashboardReportsOperationIndexRoute
  '/dashboard/reports-services': typeof AuthDashboardReportsServicesIndexRoute
  '/services/history': typeof AuthServicesHistoryIndexRoute
  '/services/ongoing': typeof AuthServicesOngoingIndexRoute
  '/services/quotes': typeof AuthServicesQuotesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/_components/Features': typeof ComponentsFeaturesRoute
  '/_components/Input': typeof ComponentsInputRoute
  '/_components/Modal': typeof ComponentsModalRoute
  '/_components/Plans': typeof ComponentsPlansRoute
  '/_register/registerAccount': typeof RegisterRegisterAccountRoute
  '/_register/registerSubdomain': typeof RegisterRegisterSubdomainRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/_auth/clients/': typeof AuthClientsIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/mechanicals/': typeof AuthMechanicalsIndexRoute
  '/_auth/services/': typeof AuthServicesIndexRoute
  '/_auth/vehicles/': typeof AuthVehiclesIndexRoute
  '/_auth/mechanicals/_components/create': typeof AuthMechanicalsComponentsCreateRoute
  '/_auth/dashboard/reports-mechanicals/': typeof AuthDashboardReportsMechanicalsIndexRoute
  '/_auth/dashboard/reports-operation/': typeof AuthDashboardReportsOperationIndexRoute
  '/_auth/dashboard/reports-services/': typeof AuthDashboardReportsServicesIndexRoute
  '/_auth/services/history/': typeof AuthServicesHistoryIndexRoute
  '/_auth/services/ongoing/': typeof AuthServicesOngoingIndexRoute
  '/_auth/services/quotes/': typeof AuthServicesQuotesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/about'
    | '/Features'
    | '/Input'
    | '/Modal'
    | '/Plans'
    | '/registerAccount'
    | '/registerSubdomain'
    | '/auth/google/callback'
    | '/clients'
    | '/dashboard'
    | '/mechanicals'
    | '/services'
    | '/vehicles'
    | '/mechanicals/create'
    | '/dashboard/reports-mechanicals'
    | '/dashboard/reports-operation'
    | '/dashboard/reports-services'
    | '/services/history'
    | '/services/ongoing'
    | '/services/quotes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/about'
    | '/Features'
    | '/Input'
    | '/Modal'
    | '/Plans'
    | '/registerAccount'
    | '/registerSubdomain'
    | '/auth/google/callback'
    | '/clients'
    | '/dashboard'
    | '/mechanicals'
    | '/services'
    | '/vehicles'
    | '/mechanicals/create'
    | '/dashboard/reports-mechanicals'
    | '/dashboard/reports-operation'
    | '/dashboard/reports-services'
    | '/services/history'
    | '/services/ongoing'
    | '/services/quotes'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/about'
    | '/_components/Features'
    | '/_components/Input'
    | '/_components/Modal'
    | '/_components/Plans'
    | '/_register/registerAccount'
    | '/_register/registerSubdomain'
    | '/auth/google/callback'
    | '/_auth/clients/'
    | '/_auth/dashboard/'
    | '/_auth/mechanicals/'
    | '/_auth/services/'
    | '/_auth/vehicles/'
    | '/_auth/mechanicals/_components/create'
    | '/_auth/dashboard/reports-mechanicals/'
    | '/_auth/dashboard/reports-operation/'
    | '/_auth/dashboard/reports-services/'
    | '/_auth/services/history/'
    | '/_auth/services/ongoing/'
    | '/_auth/services/quotes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ComponentsFeaturesRoute: typeof ComponentsFeaturesRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsModalRoute: typeof ComponentsModalRoute
  ComponentsPlansRoute: typeof ComponentsPlansRoute
  RegisterRegisterAccountRoute: typeof RegisterRegisterAccountRoute
  RegisterRegisterSubdomainRoute: typeof RegisterRegisterSubdomainRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AboutLazyRoute: AboutLazyRoute,
  ComponentsFeaturesRoute: ComponentsFeaturesRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsModalRoute: ComponentsModalRoute,
  ComponentsPlansRoute: ComponentsPlansRoute,
  RegisterRegisterAccountRoute: RegisterRegisterAccountRoute,
  RegisterRegisterSubdomainRoute: RegisterRegisterSubdomainRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login",
        "/register",
        "/about",
        "/_components/Features",
        "/_components/Input",
        "/_components/Modal",
        "/_components/Plans",
        "/_register/registerAccount",
        "/_register/registerSubdomain",
        "/auth/google/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/clients/",
        "/_auth/dashboard/",
        "/_auth/mechanicals/",
        "/_auth/services/",
        "/_auth/vehicles/",
        "/_auth/mechanicals/_components/create",
        "/_auth/dashboard/reports-mechanicals/",
        "/_auth/dashboard/reports-operation/",
        "/_auth/dashboard/reports-services/",
        "/_auth/services/history/",
        "/_auth/services/ongoing/",
        "/_auth/services/quotes/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_components/Features": {
      "filePath": "_components/Features.tsx"
    },
    "/_components/Input": {
      "filePath": "_components/Input.tsx"
    },
    "/_components/Modal": {
      "filePath": "_components/Modal.tsx"
    },
    "/_components/Plans": {
      "filePath": "_components/Plans.tsx"
    },
    "/_register/registerAccount": {
      "filePath": "_register/registerAccount.tsx"
    },
    "/_register/registerSubdomain": {
      "filePath": "_register/registerSubdomain.tsx"
    },
    "/auth/google/callback": {
      "filePath": "auth/google/callback.tsx"
    },
    "/_auth/clients/": {
      "filePath": "_auth/clients/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard/": {
      "filePath": "_auth/dashboard/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/mechanicals/": {
      "filePath": "_auth/mechanicals/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/services/": {
      "filePath": "_auth/services/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/vehicles/": {
      "filePath": "_auth/vehicles/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/mechanicals/_components/create": {
      "filePath": "_auth/mechanicals/_components/create.tsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard/reports-mechanicals/": {
      "filePath": "_auth/dashboard/reports-mechanicals/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard/reports-operation/": {
      "filePath": "_auth/dashboard/reports-operation/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard/reports-services/": {
      "filePath": "_auth/dashboard/reports-services/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/services/history/": {
      "filePath": "_auth/services/history/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/services/ongoing/": {
      "filePath": "_auth/services/ongoing/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/services/quotes/": {
      "filePath": "_auth/services/quotes/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
